### PR TITLE
Test versions

### PR DESCRIPTION
**Pull request by ayoubelmhamdi**

### CODE REVIEW

**Comment by 35713N** [comment]
hi thank you for your contribution, i deeply apologize for the late response.

i notice that your pr throws an exception (line 17) if the model is not supported by the provider. perhaps it should simply not include it in the list instead of raising an exception?

**Comment by 35713N** [comment]
also, since i have not sorted out the licensing yet, please agree:
by submitting this pull request you grant the authors of this repo the rights to distribute, sublicense, sell, modify, use, and otherwise deal in the software without restriction, and that you have the necessary rights to grant this license.

**Comment by 35713N** [comment]
ping @ayoubelmhamdi

**Comment by ayoubelmhamdi** [comment]
The [gpt4free license is GPL-3.0](https://github.com/xtekky/gpt4free/blob/main/LICENSE). I believe that when we use this repository [gpt4free](https://github.com/xtekky/gpt4free), we should use a compatible license, such as GPL-3.0.

 In GPL-3.0:

>  For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.

I believe I am using GPL-3.0 correctly. Is this correct or could there be a mistake?

**Comment by 35713N** [comment]
yes sorry this is agpl v3

**Comment by 35713N** [comment]
> hi thank you for your contribution, i deeply apologize for the late response.
>
> i notice that your pr throws an exception (line 17) if the model is not supported by the provider. perhaps it should simply not include it in the list instead of raising an exception?

was wondering if you could address ^^

**Comment by 35713N** [comment]
oh i see never mind sorry about that i will merge asap

**Comment by ayoubelmhamdi** [comment]
> i notice that your pr throws an exception (line 17) if the model is not supported by the provider. perhaps it should simply not include it in the list instead of raising an exception?

The exception thrown when the Provider does not support the model is helpful for searching for the specific version of GPT. If the provider supports the model, then we should test if it is working or not.

**Pull request merged**
